# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - APP_PORT=${APP_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432  # Use the default PostgreSQL port inside the Docker network
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d
    ports:
      - '5434:5432'  # Map the default PostgreSQL port (5432) to a different port (5434) on the host machine

volumes:
  pgdata: