version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: npm start
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
    volumes:
      - .:/usr/src/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db

volumes:
  pgdata: